services:
  frontend:
    image: registry.gitlab.com/science_space/frontend/frontend:${VERSION}
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - space_network

networks:
  space_network:
    driver: bridge
